# Generated by Django 3.0 on 2020-12-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GkQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('Option1', models.CharField(max_length=200)),
                ('Option2', models.CharField(max_length=200)),
                ('Option3', models.CharField(max_length=200)),
                ('Option4', models.CharField(max_length=200)),
                ('Corrans', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('Option1', models.CharField(max_length=200)),
                ('Option2', models.CharField(max_length=200)),
                ('Option3', models.CharField(max_length=200)),
                ('Option4', models.CharField(max_length=200)),
                ('Corrans', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SportsQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('Option1', models.CharField(max_length=200)),
                ('Option2', models.CharField(max_length=200)),
                ('Option3', models.CharField(max_length=200)),
                ('Option4', models.CharField(max_length=200)),
                ('Corrans', models.CharField(max_length=200)),
            ],
        ),
    ]
